name: master

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - uses: actions/checkout@v3

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run gulp build task
        run: ./node_modules/gulp/bin/gulp.js build

      - name: Sync acamn.org
        env:
          dest: "acamn@35.202.227.133:/sites/acamn.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}

      - name: Sync ascensionmpls.org
        env:
          dest: "ascensionmpls@35.202.227.133:/sites/ascensionmpls.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}

      - name: Sync ascensionschoolmn.org
        env:
          dest: "ascensionschoolmn@35.202.227.133:/sites/ascensionschoolmn.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}

      - name: Sync johnpaulschoolmn.org
        env:
          dest: "ascension@35.202.227.133:/sites/johnpaulschoolmn.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}

      - name: Sync stpclaverschool.org
        env:
          dest: "claver@35.202.227.133:/sites/stpclaverschool.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}

      - name: Sync stpascalschool.org
        env:
          dest: "stpascal2023@34.66.217.167:/sites/stpascalschool.org/files/wp-content/themes/ascension"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /node_modules/ \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            ./ ${{env.dest}}